grader 2.0/grader/grader/Controllers/StudentAssessmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grader.Models;
using Microsoft.AspNetCore.Http;

namespace grader.Controllers
{
    public class StudentAssessmentsController : Controller
    {
        private readonly graderContext _context;

        public StudentAssessmentsController(graderContext context)
        {
            _context = context;
        }

        // GET: StudentAssessments
        public async Task<IActionResult> Index(int? id)
        {
            var getAssessments = (from a in _context.Assessments
                                  where a.courseID.Equals(id)
                                  select a).ToList();
            return View(getAssessments);
        }

        // GET: StudentAssessments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assessment = await _context.Assessments
                .SingleOrDefaultAsync(m => m.assessmentID == id);
            if (assessment == null)
            {
                return NotFound();
            }

            return View(assessment);
        }

        // GET: StudentAssessments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StudentAssessments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("assessmentID,courseID,assessmentTotalMark,assessmentWeighting")] Assessment assessment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(assessment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assessment);
        }

        // GET: StudentAssessments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assessment = await _context.Assessments.SingleOrDefaultAsync(m => m.assessmentID == id);
            if (assessment == null)
            {
                return NotFound();
            }
            return View(assessment);
        }

        // POST: StudentAssessments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("assessmentID,courseID,assessmentTotalMark,assessmentWeighting")] Assessment assessment)
        {
            if (id != assessment.assessmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(assessment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssessmentExists(assessment.assessmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(assessment);
        }

        // GET: StudentAssessments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assessment = await _context.Assessments
                .SingleOrDefaultAsync(m => m.assessmentID == id);
            if (assessment == null)
            {
                return NotFound();
            }

            return View(assessment);
        }

        // POST: StudentAssessments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var assessment = await _context.Assessments.SingleOrDefaultAsync(m => m.assessmentID == id);
            _context.Assessments.Remove(assessment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssessmentExists(int id)
        {
            return _context.Assessments.Any(e => e.assessmentID == id);
        }
    }
}

grader 2.0/grader/grader/Controllers/StudentMarksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grader.Models;

namespace grader.Controllers
{
    public class StudentMarksController : Controller
    {
        private readonly graderContext _context;

        public StudentMarksController(graderContext context)
        {
            _context = context;
        }

        public ActionResult Approve()
        {
            return View();
        }

        // GET: StudentMarks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Marks.ToListAsync());
        }

        // GET: StudentMarks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks
                .SingleOrDefaultAsync(m => m.markID == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // GET: StudentMarks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StudentMarks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("markID,studentID,assessmentID,markAchieved")] Mark mark)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mark);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mark);
        }

        // GET: StudentMarks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks.SingleOrDefaultAsync(m => m.markID == id);
            if (mark == null)
            {
                return NotFound();
            }
            return View(mark);
        }

        // POST: StudentMarks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("markID,studentID,assessmentID,markAchieved")] Mark mark)
        {
            if (id != mark.markID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mark);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarkExists(mark.markID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mark);
        }

        // GET: StudentMarks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks
                .SingleOrDefaultAsync(m => m.markID == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // POST: StudentMarks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mark = await _context.Marks.SingleOrDefaultAsync(m => m.markID == id);
            _context.Marks.Remove(mark);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarkExists(int id)
        {
            return _context.Marks.Any(e => e.markID == id);
        }
    }
}

grader 2.0/grader/grader/Views/StudentAssessments/Create.cshtml
@model grader.Models.Assessment

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Assessment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="courseID" class="control-label"></label>
                <input asp-for="courseID" class="form-control" />
                <span asp-validation-for="courseID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="assessmentTotalMark" class="control-label"></label>
                <input asp-for="assessmentTotalMark" class="form-control" />
                <span asp-validation-for="assessmentTotalMark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="assessmentWeighting" class="control-label"></label>
                <input asp-for="assessmentWeighting" class="form-control" />
                <span asp-validation-for="assessmentWeighting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


grader 2.0/grader/grader/Views/StudentAssessments/Delete.cshtml
@model grader.Models.Assessment

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assessment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.courseID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.courseID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.assessmentTotalMark)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.assessmentTotalMark)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.assessmentWeighting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.assessmentWeighting)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="assessmentID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

grader 2.0/grader/grader/Views/StudentAssessments/Details.cshtml
@model grader.Models.Assessment

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Assessment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.courseID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.courseID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.assessmentTotalMark)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.assessmentTotalMark)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.assessmentWeighting)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.assessmentWeighting)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.assessmentID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

grader 2.0/grader/grader/Views/StudentAssessments/Edit.cshtml
@model grader.Models.Assessment

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Assessment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="assessmentID" />
            <div class="form-group">
                <label asp-for="courseID" class="control-label"></label>
                <input asp-for="courseID" class="form-control" />
                <span asp-validation-for="courseID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="assessmentTotalMark" class="control-label"></label>
                <input asp-for="assessmentTotalMark" class="form-control" />
                <span asp-validation-for="assessmentTotalMark" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="assessmentWeighting" class="control-label"></label>
                <input asp-for="assessmentWeighting" class="form-control" />
                <span asp-validation-for="assessmentWeighting" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


grader 2.0/grader/grader/Views/StudentAssessments/Index.cshtml
@model IEnumerable<grader.Models.Assessment>

@{
    ViewData["Title"] = "Index";
}
<br />
<br />
<h2>Assessments</h2>
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                Assessment Name
            </th>
                <th>
                    Total Mark
                </th>
                <th>
                    Weighting
                </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.assessmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.assessmentTotalMark)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.assessmentWeighting)
            </td>
            <td>
                <a asp-controller="StudentMarks" asp-action="Details" asp-route-id="@item.assessmentID">View Marks</a> 
            </td>
        </tr>
}
    </tbody>
</table>