grader 2.0/grader/grader/Controllers/StudentHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grader.Models;

namespace grader.Controllers
{
    public class StudentHomeController : Controller
    {
        private readonly graderContext _context;

        public StudentHomeController(graderContext context)
        {
            _context = context;
        }

        // GET: StudentHome
        public async Task<IActionResult> Index()
        {
            int tempStudentID = 1;
            var getStudentCourses = (from s in _context.StudentCourses
                                     where s.studentID.Equals(tempStudentID)
                                     select s.courseID).ToList();
            List<Course> courseList = new List<Course>();
            for (int i = 0; i < getStudentCourses.Count(); i++)
            {
                var getCourse = (from c in _context.Courses
                                 where c.courseID == getStudentCourses[i]
                                 select c).SingleOrDefault();
                courseList.Add(getCourse);
            }
            return View(courseList);
        }

        // GET: StudentHome/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .SingleOrDefaultAsync(m => m.courseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: StudentHome/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StudentHome/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("courseID,courseName,courseCode,courseCoordinatorID,schoolAdministratorID")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: StudentHome/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.SingleOrDefaultAsync(m => m.courseID == id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: StudentHome/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("courseID,courseName,courseCode,courseCoordinatorID,schoolAdministratorID")] Course course)
        {
            if (id != course.courseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.courseID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: StudentHome/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .SingleOrDefaultAsync(m => m.courseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: StudentHome/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.SingleOrDefaultAsync(m => m.courseID == id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.courseID == id);
        }
    }
}

grader 2.0/grader/grader/Controllers/StudentMarksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grader.Models;

namespace grader.Controllers
{
    public class StudentMarksController : Controller
    {
        private readonly graderContext _context;

        public StudentMarksController(graderContext context)
        {
            _context = context;
        }

        public ActionResult Approve()
        {
            return View();
        }

        // GET: StudentMarks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Marks.ToListAsync());
        }

        // GET: StudentMarks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks
                .SingleOrDefaultAsync(m => m.markID == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // GET: StudentMarks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: StudentMarks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("markID,studentID,assessmentID,markAchieved")] Mark mark)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mark);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mark);
        }

        // GET: StudentMarks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks.SingleOrDefaultAsync(m => m.markID == id);
            if (mark == null)
            {
                return NotFound();
            }
            return View(mark);
        }

        // POST: StudentMarks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("markID,studentID,assessmentID,markAchieved")] Mark mark)
        {
            if (id != mark.markID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mark);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MarkExists(mark.markID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mark);
        }

        // GET: StudentMarks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Marks
                .SingleOrDefaultAsync(m => m.markID == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // POST: StudentMarks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mark = await _context.Marks.SingleOrDefaultAsync(m => m.markID == id);
            _context.Marks.Remove(mark);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MarkExists(int id)
        {
            return _context.Marks.Any(e => e.markID == id);
        }
    }
}

grader 2.0/grader/grader/Views/StudentMarks/Approve.cshtml

@{
    ViewData["Title"] = "Approve";
}

<br />
<br />
<h2>Query Successfully Sent</h2>
<br />
<form asp-action="Index" asp-controller="StudentHome">
    <input type="submit" value="Home" />
</form>



grader 2.0/grader/grader/Views/StudentMarks/Create.cshtml
@model grader.Models.Mark

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Mark</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="studentID" class="control-label"></label>
                <input asp-for="studentID" class="form-control" />
                <span asp-validation-for="studentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="assessmentID" class="control-label"></label>
                <input asp-for="assessmentID" class="form-control" />
                <span asp-validation-for="assessmentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="markAchieved" class="control-label"></label>
                <input asp-for="markAchieved" class="form-control" />
                <span asp-validation-for="markAchieved" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


grader 2.0/grader/grader/Views/StudentMarks/Delete.cshtml
@model grader.Models.Mark

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mark</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.studentID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.studentID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.assessmentID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.assessmentID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.markAchieved)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.markAchieved)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="markID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

grader 2.0/grader/grader/Views/StudentMarks/Details.cshtml
@model grader.Models.Mark

@{
    ViewData["Title"] = "Details";
}
<br />
<br />
<h2>Assessment Mark</h2>
<br />
<div>
    
    <hr />
    <h4>
        <dl class="dl-horizontal">
            <dt>
                Mark Achieved:
            </dt>
            <dd>
                @Html.DisplayFor(model => model.markAchieved)
            </dd>
        </dl>
    </h4>
</div>
<div>
    <a asp-action="Approve" asp-route-id="@Model.markID">Query</a> 
    
</div>


grader 2.0/grader/grader/Views/StudentMarks/Edit.cshtml
@model grader.Models.Mark

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Mark</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="markID" />
            <div class="form-group">
                <label asp-for="studentID" class="control-label"></label>
                <input asp-for="studentID" class="form-control" />
                <span asp-validation-for="studentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="assessmentID" class="control-label"></label>
                <input asp-for="assessmentID" class="form-control" />
                <span asp-validation-for="assessmentID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="markAchieved" class="control-label"></label>
                <input asp-for="markAchieved" class="form-control" />
                <span asp-validation-for="markAchieved" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


grader 2.0/grader/grader/Views/StudentMarks/Index.cshtml
@model IEnumerable<grader.Models.Mark>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.studentID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.assessmentID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.markAchieved)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.studentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.assessmentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.markAchieved)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.markID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.markID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.markID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>