grader 2.0/grader/grader/Controllers/CCHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grader.Models;

namespace grader.Controllers
{
    public class CCHomeController : Controller
    {
        private readonly graderContext _context;

        public CCHomeController(graderContext context)
        {
            _context = context;
        }

        // GET: CCHome
        public async Task<IActionResult> Index()
        {
            int tempCCid = 1;
            var getCourses = (from c in _context.Courses
                              where c.courseCoordinatorID == tempCCid
                              select c).ToList();
            return View(getCourses);
        }

        // GET: CCHome/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .SingleOrDefaultAsync(m => m.courseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: CCHome/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CCHome/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("courseID,courseName,courseCode,courseCoordinatorID,schoolAdministratorID")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: CCHome/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.SingleOrDefaultAsync(m => m.courseID == id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: CCHome/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("courseID,courseName,courseCode,courseCoordinatorID,schoolAdministratorID")] Course course)
        {
            if (id != course.courseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.courseID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: CCHome/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .SingleOrDefaultAsync(m => m.courseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: CCHome/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.SingleOrDefaultAsync(m => m.courseID == id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.courseID == id);
        }
    }
}

grader 2.0/grader/grader/Controllers/OffencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grader.Models;

namespace grader.Controllers
{
    public class OffencesController : Controller
    {
        private readonly graderContext _context;

        public OffencesController(graderContext context)
        {
            _context = context;
        }

        // GET: Offences
        public async Task<IActionResult> Index()
        {
            var getOffences = (from r in _context.ReportQueries
                               where r.reportQueryNature == "offence"
                               select r).ToList();
            return View(getOffences);
        }

        // GET: Offences/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportQuery = await _context.ReportQueries
                .SingleOrDefaultAsync(m => m.reportQueryID == id);
            if (reportQuery == null)
            {
                return NotFound();
            }

            return View(reportQuery);
        }

        // GET: Offences/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Offences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("reportQueryID,studentID,reportQueryNature,reportQueryReason,reportQueryValid")] ReportQuery reportQuery)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reportQuery);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reportQuery);
        }

        // GET: Offences/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportQuery = await _context.ReportQueries.SingleOrDefaultAsync(m => m.reportQueryID == id);
            if (reportQuery == null)
            {
                return NotFound();
            }
            return View(reportQuery);
        }

        // POST: Offences/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("reportQueryID,studentID,reportQueryNature,reportQueryReason,reportQueryValid")] ReportQuery reportQuery)
        {
            if (id != reportQuery.reportQueryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reportQuery);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReportQueryExists(reportQuery.reportQueryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reportQuery);
        }

        // GET: Offences/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reportQuery = await _context.ReportQueries
                .SingleOrDefaultAsync(m => m.reportQueryID == id);
            if (reportQuery == null)
            {
                return NotFound();
            }

            return View(reportQuery);
        }

        // POST: Offences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reportQuery = await _context.ReportQueries.SingleOrDefaultAsync(m => m.reportQueryID == id);
            _context.ReportQueries.Remove(reportQuery);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReportQueryExists(int id)
        {
            return _context.ReportQueries.Any(e => e.reportQueryID == id);
        }
    }
}

grader 2.0/grader/grader/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace grader.Controllers
{
    public class ReportsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult SAReports()
        {
            return View();
        }

        public ActionResult CCReports()
        {
            return View();
        }

    }
}

grader 2.0/grader/grader/Controllers/SACCAssessmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using grader.Models;
using Microsoft.AspNetCore.Http;

namespace grader.Controllers
{
    public class SACCAssessmentsController : Controller
    {
        private readonly graderContext _context;

        public SACCAssessmentsController(graderContext context)
        {
            _context = context;
        }

        // GET: SACCAssessments
        public async Task<IActionResult> Index(int? id)
        {
            var getAssessments = (from a in _context.Assessments
                                  where a.courseID == id
                                  select a).ToList();

            return View(getAssessments);
        }

        


        // GET: SACCAssessments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assessment = await _context.Assessments
                .SingleOrDefaultAsync(m => m.assessmentID == id);
            if (assessment == null)
            {
                return NotFound();
            }

            return View(assessment);
        }

        // GET: SACCAssessments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: SACCAssessments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("assessmentID,courseID,assessmentTotalMark,assessmentWeighting,assessmentName")] Assessment assessment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(assessment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assessment);
        }

        // GET: SACCAssessments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assessment = await _context.Assessments.SingleOrDefaultAsync(m => m.assessmentID == id);
            if (assessment == null)
            {
                return NotFound();
            }
            return View(assessment);
        }

        // POST: SACCAssessments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("assessmentID,courseID,assessmentTotalMark,assessmentWeighting,assessmentName")] Assessment assessment)
        {
            if (id != assessment.assessmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(assessment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssessmentExists(assessment.assessmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(assessment);
        }

        // GET: SACCAssessments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assessment = await _context.Assessments
                .SingleOrDefaultAsync(m => m.assessmentID == id);
            if (assessment == null)
            {
                return NotFound();
            }

            return View(assessment);
        }

        // POST: SACCAssessments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var assessment = await _context.Assessments.SingleOrDefaultAsync(m => m.assessmentID == id);
            _context.Assessments.Remove(assessment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssessmentExists(int id)
        {
            return _context.Assessments.Any(e => e.assessmentID == id);
        }
    }
}

grader 2.0/grader/grader/Views/SAHome/Create.cshtml
@model grader.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="courseName" class="control-label"></label>
                <input asp-for="courseName" class="form-control" />
                <span asp-validation-for="courseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="courseCode" class="control-label"></label>
                <input asp-for="courseCode" class="form-control" />
                <span asp-validation-for="courseCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="courseCoordinatorID" class="control-label"></label>
                <input asp-for="courseCoordinatorID" class="form-control" />
                <span asp-validation-for="courseCoordinatorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="schoolAdministratorID" class="control-label"></label>
                <input asp-for="schoolAdministratorID" class="form-control" />
                <span asp-validation-for="schoolAdministratorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


grader 2.0/grader/grader/Views/SAHome/Delete.cshtml
@model grader.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.courseName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.courseName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.courseCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.courseCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.courseCoordinatorID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.courseCoordinatorID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.schoolAdministratorID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.schoolAdministratorID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="courseID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

grader 2.0/grader/grader/Views/SAHome/Details.cshtml
@model grader.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.courseName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.courseName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.courseCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.courseCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.courseCoordinatorID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.courseCoordinatorID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.schoolAdministratorID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.schoolAdministratorID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.courseID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

grader 2.0/grader/grader/Views/SAHome/Edit.cshtml
@model grader.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="courseID" />
            <div class="form-group">
                <label asp-for="courseName" class="control-label"></label>
                <input asp-for="courseName" class="form-control" />
                <span asp-validation-for="courseName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="courseCode" class="control-label"></label>
                <input asp-for="courseCode" class="form-control" />
                <span asp-validation-for="courseCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="courseCoordinatorID" class="control-label"></label>
                <input asp-for="courseCoordinatorID" class="form-control" />
                <span asp-validation-for="courseCoordinatorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="schoolAdministratorID" class="control-label"></label>
                <input asp-for="schoolAdministratorID" class="form-control" />
                <span asp-validation-for="schoolAdministratorID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


grader 2.0/grader/grader/Views/SAHome/Index.cshtml
@model IEnumerable<grader.Models.Course>

@{
    ViewData["Title"] = "Index";
}
<!---EDIT THIS ONE-->
<br />
<br />
<table>
    <tr width="100%">
        <th width="38%">
            <a asp-controller="CCHome" asp-action="Create">
                <input type="submit" value="Add Course" style="color:black" />
            </a>
        </th>
        <th width="38%">
            <a asp-controller="Reports" asp-action="SAreports">
                <input type="submit" value="View Reports" style="color:black" />
            </a>
        </th>
        <th width="38%">
            <a asp-controller="Offences" asp-action="Index">
                <input type="submit" value="View Offences" style="color:black" />
            </a>
        </th>
    </tr>

</table>
<br />
<h2>My Courses</h2>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                Course Name
            </th>
            <th>
                Course Code
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.courseName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.courseCode)
                </td>
                <td>
                    <a asp-action="Index" asp-controller="SACCAssessments" asp-route-id="@item.courseID">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<form>
    <input type="hidden" value="CC" name="type" />
</form>